### ISSUE TITLE
Add vendor to .gitignore

### ISSUE THREAD

**Issue by rjd22** [arout/diamondphp#2]
Since `composer.json` and `composer.lock`. Will keep your dependencies up-to-date I would recommend ignoring the vendor directory with `.gitignore`.

See here for more information on this:
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by arout** [comment]
Thank you for reporting this, rjd22! I'll make this correction shortly.

**Comment by arout** [comment]
.gitignore added to ignore vendor directory. Closing issue. As always, thank you for your feedback and helping Diamond PHP grow!

**Comment by rjd22** [comment]
@arout Make sure to remove the vendor directory in your repository. Else it will still be there.

**Comment by arout** [comment]
Thank you for catching this oversight. Ignoring vendor directory will significantly reduce the file size for download/cloning, which was already a big concern.
