### ISSUE TITLE
declare(strict_types=1); should be declared per file

### ISSUE THREAD

**Issue by jelrikvh** [arout/diamondphp#4]
In https://github.com/arout/diamondphp/blob/master/app/code/core/system/global.php#L6, a global `declare(strict_types=1);` is called. This command, however, works on a per-file basis and should therefor be the first operation in every single PHP file in the repo to take any effect.

Currently, it only affects calls to methods and functions declared inside `app/code/core/system/global.php`, but there aren't any there.

For more information, please refer to http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict

**Comment by arout** [comment]
References to strict types removed. Closing issue. As always, thank you for your feedback and helping Diamond PHP grow!

**Comment by arnovr** [comment]
I agree with jelrikvh, therefor a PR to help you add strict types.

https://github.com/arout/diamondphp/pull/7

**Comment by arout** [comment]
Thank you, arnover. Pull request merged.
