### ISSUE TITLE
Make framework code unreachable to clients

### ISSUE THREAD

**Issue by yamitenshi** [arout/diamondphp#5]
At this time, access to the core/module code is mitigated by having an `index.html` file in each module, but this is far from secure - anyone with knowledge of the project's structure could reach arbitrary files by simply typing their path into the address bar of their browser.

Ideally, this would mean having a separate web root that does not contain any core/module code and/or templates, but instead only contains the `index.php` file and whatever frontend assets need to be reachable from the client's browser.

**Comment by arout** [comment]
yamitenshi - Thank you very much for catching that and your feedback. I will be correcting this issue very soon.

The documentation is still a work in progress and will not be completed for at least a few more weeks, but something that I wanted to stress was the importance of moving _everything_, other than the front controller, htaccess and /media folder, above the web root. I believe the instructions on how to do so are already in the docs, but again, I agree that this should be encouraged.

Regards,

Andrew

**Comment by arout** [comment]
Documentation on moving core files out of web root completed. Closing issue. As always, thank you for your feedback and helping Diamond PHP grow!
