### ISSUE TITLE
Use environment configuration file to populate /app/code/core/config/Config.php

### ISSUE THREAD

**Issue by Caroga** [arout/diamondphp#6]
Instead of having a static configuration per project you could make use of an environment file that populates generic Config settings. 

Example:
Project A will be released under a different branch name, now you have to clone the repo and commit configuration changes, or adjust them manually. Database credentials is a perfect example.
Using a (generated) environment file you don't have this inside your codebase. 

Take a look at: https://github.com/vlucas/phpdotenv.
or, if still alive: https://github.com/hassankhan/config

**Comment by arout** [comment]
I think this is an excellent idea! Thank you very much for your feedback; I will look into implementing this in the very near future.

Regards,

Andrew

**Comment by Caroga** [comment]
No problem. I actually was planning on providing a PR for you, maybe tonight or tomorrow.

**Comment by arout** [comment]
I particularly like https://github.com/vlucas/phpdotenv. It seems that will be fairly straightforward to integrate with the existing code; especially important since the existing Config settings are used all over the place in the framework.

**Comment by arout** [comment]
Wrote a custom configuration importer; the Config.php file now pulls value set in a .env file (currently stored in root dir; should be moved when deployed).
